http:
  host: 0.0.0.0
  port: 8080
log:
  level: info
  encoding: console
  file: logs/ezchat.log
  max_size_mb: 50
  max_backups: 7
  max_age_days: 14
  compress: true
  console: true
db:
  dsn: root:root@tcp(127.0.0.1:3306)/ezchat?charset=utf8mb4&parseTime=True&loc=Local
  max_open_conns: 20
  max_idle_conns: 10
  conn_max_idle_sec: 300
  conn_max_life_sec: 3600

